---
abstract: 'A handy collection of small PPI-based utilities'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IPC::Run3: 0.034
  Probe::Perl: 0.01
  Test::More: 0.47
  Test::Script: 1.03
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PPI::PowerToys
name: PPI-PowerToys
no_index:
  directory:
    - inc
    - t
requires:
  File::Find::Rule: 0.30
  File::Find::Rule::Perl: 0.03
  File::Spec: 0.80
  PPI::Document: 1.201
  perl: 5.6.0
  version: 0.74
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/PPI-PowerToys
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/PPI-PowerToys
version: 0.13
